package com.me.based;

import java.awt.Canvas;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.image.BufferStrategy;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferInt;

import javax.swing.JFrame;

import com.me.based.entity.mob.Player;
import com.me.based.graphics.Screen;
import com.me.based.input.Keyboard;
import com.me.based.level.Level;
import com.me.based.level.RandomLevel;

public class Game extends Canvas implements Runnable {

	private static final long serialVersionUID = 1L;
	public static String title = "Based";
	public static int width = 300;
	public static int height = 168;
	public static int scale = 3;

	private Thread thread;
	private JFrame frame;
	private Keyboard key;
	private Level level;
	private Player player;
	
	private boolean running = false;

	private Screen screen;

	//an image with an accessible buffer
	private BufferedImage image = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
	//this converts the image object into an array of integers
	private int[] pixels = ((DataBufferInt) image.getRaster().getDataBuffer()).getData();

	public Game() {
		Dimension size = new Dimension(width * scale, height * scale);
		this.setPreferredSize(size);
		screen = new Screen(width, height);
		frame = new JFrame();
		
		//listen for keyboard inputs
		key = new Keyboard();
		
		level = new RandomLevel(64,64);
		player = new Player(key);
		
		this.addKeyListener(key);
	}

	public synchronized void start() {
		running = true;
		thread = new Thread(this, "Display");
		thread.start();
	}

	public synchronized void stop() {
		running = false;
		try {
			thread.join();
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}

	// will loop forever as long as the thread is active
	public void run() {
		
		//gets focus for the window
		this.requestFocus();
		
		long last_time = System.nanoTime();
		long timer = System.currentTimeMillis();
		//1000000000 is 1 second in nano seconds
		//ns divides up that second into x number of frames
		final double ns = 1000000000.0 / 60.0;
		double delta = 0;
		int frames = 0;
		int updates = 0;
		while (running) {
			long now = System.nanoTime();
			delta += (now - last_time) / ns;
			last_time = now;
			// update is only called x times per second per ns variable
			while (delta >= 1) {
				update();
				updates++;
				delta--;
			}

			// render is called as fast as can be handled
			render();
			frames++;

			//this is only run every 1000 milliseconds = 1 second
			if (System.currentTimeMillis() - timer > 1000) {
				timer += 1000;
				frame.setTitle(title + "  |  " + updates + " ups, " + frames + " FPS");
				updates = 0;
				frames = 0;
			}
		}
		stop();
	}

	

	public void update() {
		key.update();
		player.update();
	}

	public void render() {
		// assign the bs of the canvas to bs
		BufferStrategy bs = this.getBufferStrategy();

		// if the bufferstrategy doesn't exist, create it
		if (bs == null) {
			this.createBufferStrategy(3);
			return;
		}

		screen.clear();
		//renders the level and sets the player in the centre
		level.render(player.get_x()-(width/2), player.get_y()-(height/2), screen);
		//render the player
		player.render(screen);
		//assign all the pixels generated by screen class into pixels for rendering
		for (int i = 0; i < pixels.length; i++) {
			pixels[i] = screen.pixels[i];
		}

		Graphics g = bs.getDrawGraphics();
		// all drawing to screen happens between here and dispose() method
		g.drawImage(image, 0, 0, getWidth(), getHeight(), null);
		
		g.setColor(Color.WHITE);
		g.setFont(new Font("Verdana", 0, 50));
		g.drawString("x " + player.get_x() + "  y " + player.get_y(), 500, 480);
		//
		g.dispose();
		bs.show();
	}

	public static void main(String[] args) {
		Game game = new Game();
		game.frame.setResizable(false);
		game.frame.setTitle(title);
		game.frame.add(game);
		game.frame.pack();
		game.frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		game.frame.setLocationRelativeTo(null);
		game.frame.setVisible(true);
		game.start();
	}

}
